/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// ? Old Config Details
// const awsconfig = {
//     aws_project_region: 'ap-south-1',
//     aws_cognito_identity_pool_id: 'ap-south-1:1d7efd56-8a5b-42a9-a219-fa9d702e8ad7',
//     aws_cognito_region: 'ap-south-1',
//     aws_user_pools_id: 'ap-south-1_JjVGYAO1U',
//     aws_user_pools_web_client_id: '63tnetl2dteurqu9tfa9luj3l3',
//     oauth: {}
// };
// ? Old Config Details

const awsconfig = {
    aws_project_region: 'ap-south-1',
    aws_cognito_identity_pool_id: 'ap-south-1:0dffe016-e230-4e1a-939d-5ebd17da4ebe',
    aws_cognito_region: 'ap-south-1',
    aws_user_pools_id: 'ap-south-1_W68gF4pDU',
    aws_user_pools_web_client_id: '2gcbvmncimhhhkon3qukrbgdbu',
    oauth: {}
};


export default awsconfig;
